version: '3.8'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - db-network

  api:
    image: node:18
    user: node
    working_dir: /home/node/api
    volumes:
      - ./api:/home/node/api
      - ./client:/home/node/client
    env_file:
      - .env
    command: bash -c "npm install; npm run build; npm run setup; npm run start;"
    depends_on:
      - db
    networks:
      - proxy-network
      - db-network

  proxy:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client/build:/usr/share/nginx/html
    ports:
      - 8080:80
    networks:
      - proxy-network
    depends_on:
      - api

volumes:
  postgres-data:


networks:
  proxy-network:
  db-network:
